FROM ${NODE_IMAGE_NAME}:${NODE_VERSION}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 \
    libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 \
    libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 \
    libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils \
    libxshmfence1 libglu1 && \
    npm install -g stylelint@${STYLELINT_VERSION} postcss-scss@${POSTCSS_SCSS_VERSION} eslint@${ESLINT_VERSION} pa11y-ci@${PA11Y_CI_VERSION} @commitlint/cli@${COMMITLINT_VERSION} \
    pa11y-ci-reporter-html@${PA11Y_CI_REPORTER_HTML_VERSION} --unsafe-perm=true && \
    rm -rf /tmp/* && \
    rm -rf /var/lib/apt/lists/*

USER circleci
