FROM ${PHP_IMAGE_NAME}:${PHP_VERSION}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# hadolint ignore=DL3008
RUN apt-get update && \
  apt-get install --no-install-recommends -y build-essential mariadb-client subversion php-xdebug && \
  rm -rf /var/lib/apt/lists/*

USER circleci

ENV PATH="/home/circleci/.composer/vendor/bin:${PATH}"
