FROM ${PHP_IMAGE_NAME}:${PHP_VERSION}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# RUN echo 'deb http://ftp.us.debian.org/debian sid main' | tee -a /etc/apt/sources.list
# hadolint ignore=DL3009
RUN apt-get update
# hadolint ignore=DL3008
RUN apt-get install --no-install-recommends -y build-essential mariadb-client subversion php-xdebug
RUN rm -rf /var/lib/apt/lists/*

USER circleci

ENV PATH="/home/circleci/.composer/vendor/bin:${PATH}"
