FROM ${BASE_IMAGE_NAME}:${PHP_VERSION}

LABEL authors="${AUTHOR}"

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# hadolint ignore=DL3008
RUN echo 'deb http://ftp.us.debian.org/debian sid main' | tee -a /etc/apt/sources.list && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install --no-install-recommends -y \
      build-essential \
      mysql-client-5.7 \
      nodejs \
      subversion \
      && \
    rm -rf /var/lib/apt/lists/* && \
    docker-php-ext-install mysqli

RUN npm install -g \
      stylelint@${STYLELINT_VERSION} \
      eslint@${ESLINT_VERSION}

USER circleci

ENV PATH="/home/circleci/.composer/vendor/bin:${PATH}"
