FROM ${PHP_IMAGE_NAME}:${PHP_VERSION}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

# Install Composer 1.10.19
# https://github.com/greenpeace/planet4-docker/blob/master/config.default#L42
RUN composer self-update --1

# RUN echo 'deb http://ftp.us.debian.org/debian sid main' | tee -a /etc/apt/sources.list
# hadolint ignore=DL3009
RUN apt-get update
# hadolint ignore=DL3008
RUN apt-get install --no-install-recommends -y build-essential mariadb-client nodejs npm subversion
RUN rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install mysqli

USER circleci

ENV PATH="/home/circleci/.composer/vendor/bin:${PATH}"
