---
version: 2.1

docker_auth: &docker_auth
  username: $DOCKERHUB_USERNAME
  password: $DOCKERHUB_PASSWORD

defaults: &defaults
  environment:
    GOOGLE_PROJECT_ID: planet-4-151612
  docker:
    - image: greenpeaceinternational/circleci-base:latest
      auth:
        <<: *docker_auth
  working_directory: /home/circleci/app

jobs:
  build-push:
    <<: *defaults
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: bake
          command: make bake
      - run:
          name: build
          command: make build
      - run:
          name: test
          command: make test
      - run: docker-login.sh
      - run: |
          mkdir -p /tmp/workspace/var
          echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run: make -j2 push push-latest
      - store_test_results:
          path: /home/circleci/app/test/logs/
      - store_artifacts:
          path: /home/circleci/app/test/logs/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - var

  promote:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Merge from develop
          command: |
            merge-develop.sh
      - run:
          name: Tag
          command: |
            current_version=$(git-current-tag.sh)
            new_version=$(increment-version.sh $current_version)
            echo "Promoting branch ${CIRCLE_BRANCH} to ${new_version}"
            git tag -a "$new_version" -m "$new_version"
            git push origin --tags

workflows:
  version: 2
  branch:
    jobs:
      - build-push:
          context: org-global
          filters:
            branches:
              ignore: master
      - hold-promote:
          type: approval
          requires:
            - build-push
          filters:
            branches:
              only: develop
      - promote:
          context: org-global
          requires:
            - hold-promote
          filters:
            branches:
              only: develop

  tag:
    jobs:
      - build-push:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
