FROM ${NODE_IMAGE_NAME}:${NODE_IMAGE_VERSION}

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

USER root

RUN npm install -g stylelint@${STYLELINT_VERSION} eslint@${ESLINT_VERSION}

USER circleci

ENV PATH="/home/circleci/.composer/vendor/bin:${PATH}"
